"""Shared modules for the ImGui ESC configurator application."""

APP_VERSION = "0.3.0-dev"

from .app_state import AppState, ConnectionSettings, LogEntry, create_app_state
from .diagnostics_export import export_diagnostics_bundle
from .firmware_catalog import FirmwareCatalogClient, FirmwareCatalogSnapshot, FirmwareImage, FirmwareLayout, FirmwareRelease, load_firmware_file
from .runtime_logging import configure_runtime_logging, flush_runtime_logging, get_logger, get_runtime_log_path
from .settings_decoder import (
    DecodedSettings,
    ParsedSetting,
    SettingDescriptor,
    SettingOption,
    build_settings_payload,
    decode_settings_payload,
    get_editable_field_values,
)
from .worker import (
    CommandConnect,
    CommandDownloadFirmware,
    CommandDisconnect,
    CommandEnterPassthrough,
    CommandExitPassthrough,
    CommandFlashEsc,
    CommandFlashAllEscs,
    CommandRefreshFirmwareCatalog,
    CommandReadFourWayIdentity,
    CommandReadSettings,
    CommandSetMotorSpeed,
    CommandWriteSettings,
    CommandRefreshPorts,
    CommandScanEscs,
    EventAllEscsFlashed,
    EventConnected,
    EventDisconnected,
    EventEscScanResult,
    EventFirmwareCatalogLoaded,
    EventFourWayIdentity,
    EventError,
    EventLog,
    EventFirmwareDownloaded,
    EventFirmwareFlashed,
    EventPassthroughState,
    EventPortsUpdated,
    EventProgress,
    EventSettingsLoaded,
    EventSettingsWritten,
    WorkerController,
)

__all__ = [
    "APP_VERSION",
    "AppState",
    "ConnectionSettings",
    "export_diagnostics_bundle",
    "FirmwareCatalogClient",
    "FirmwareCatalogSnapshot",
    "FirmwareImage",
    "FirmwareLayout",
    "FirmwareRelease",
    "load_firmware_file",
    "configure_runtime_logging",
    "flush_runtime_logging",
    "get_logger",
    "get_runtime_log_path",
    "LogEntry",
    "DecodedSettings",
    "ParsedSetting",
    "SettingDescriptor",
    "SettingOption",
    "build_settings_payload",
    "create_app_state",
    "decode_settings_payload",
    "get_editable_field_values",
    "CommandConnect",
    "CommandDownloadFirmware",
    "CommandDisconnect",
    "CommandEnterPassthrough",
    "CommandExitPassthrough",
    "CommandFlashEsc",
    "CommandRefreshFirmwareCatalog",
    "CommandReadFourWayIdentity",
    "CommandReadSettings",
    "CommandSetMotorSpeed",
    "CommandWriteSettings",
    "CommandRefreshPorts",
    "CommandScanEscs",
    "EventConnected",
    "EventDisconnected",
    "EventEscScanResult",
    "EventFirmwareCatalogLoaded",
    "EventFourWayIdentity",
    "EventError",
    "EventFirmwareDownloaded",
    "EventFirmwareFlashed",
    "EventLog",
    "EventPassthroughState",
    "EventPortsUpdated",
    "EventProgress",
    "EventSettingsLoaded",
    "EventSettingsWritten",
    "WorkerController",
]
